#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM openjdk:8
RUN apt update \
  # procps is for `free` command
  && apt install wget unzip lsof procps -y \
  && wget -c -r -np -nc -L -p  http://172.16.125.72:8000/iotdb_2/ \
  # if you are in China, use the following URL
  #&& wget http://mirrors.tuna.tsinghua.edu.cn/apache/incubator/iotdb/0.10.1-incubating/apache-iotdb-0.10.1-incubating-bin.zip \
  && mv 172.16.125.72:8000/iotdb_2 ./ \
  && chmod 777 ./iotdb_2/sbin/* \
  && rm -rf 172.16.125.72:8000 \
  && apt remove wget unzip -y \
  && apt autoremove -y \
  && apt purge --auto-remove -y \
  && apt clean -y

EXPOSE 6668
EXPOSE 31888
EXPOSE 9005
EXPOSE 9006
EXPOSE 40012
EXPOSE 40013
EXPOSE 55561

LABEL app="iotdb-cluster-2"

VOLUME /iotdb_2/data
VOLUME /iotdb_2/logs
ENV PATH="/iotdb_2/sbin/:/iotdb_2/tools/:${PATH}"
ENTRYPOINT ["/iotdb_2/sbin/start-node.sh"]
