#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM openjdk:8
RUN apt update \
  # procps is for `free` command
  && apt install wget unzip lsof procps -y \
  && wget -c -r -np -nc -L -p  http://172.16.125.72:8000/iotdb_1/ \
  # if you are in China, use the following URL
  #&& wget http://mirrors.tuna.tsinghua.edu.cn/apache/incubator/iotdb/0.10.1-incubating/apache-iotdb-0.10.1-incubating-bin.zip \
  && mv 172.16.125.72:8000/iotdb_1 ./ \
  && chmod 777 ./iotdb_1/sbin/* \
  && rm -rf 172.16.125.72:8000 \
  && apt remove wget unzip -y \
  && apt autoremove -y \
  && apt purge --auto-remove -y \
  && apt clean -y

EXPOSE 6667
EXPOSE 31777
EXPOSE 9003
EXPOSE 9004
EXPOSE 40010
EXPOSE 40011
EXPOSE 55560
LABEL app="iotdb-cluster-1"

VOLUME /iotdb_1/data
VOLUME /iotdb_1/logs
ENV PATH="/iotdb_1/sbin/:/iotdb_1/tools/:${PATH}"
ENTRYPOINT ["/iotdb_1/sbin/start-node.sh"]
